package tech.kelma.app

internal data class AppContentActions(
    val undoReview: suspend (String) -> ReviewCard?,
    val requestSync: () -> Unit,
    val redownloadCollection: () -> Unit,
    val signIn: (String, String) -> Unit,
    val selectAccount: (LocalAccountChoice) -> Unit,
    val signOut: () -> Unit,
    val openDecks: () -> Unit,
    val openAdd: () -> Unit,
    val openBrowse: () -> Unit,
    val openOptions: () -> Unit,
    val openPlugins: () -> Unit,
    val openStats: () -> Unit,
    val openSync: () -> Unit,
    val assignPreset: suspend (String, String?) -> String?,
    val createPreset: suspend (String, String, DeckOptions) -> String?,
    val clonePreset: suspend (String, String, String) -> String?,
    val renamePreset: suspend (String, String) -> String?,
    val deletePreset: suspend (String) -> String?,
    val applyAccountSchedulerProfile: suspend (DeckOptions, Boolean) -> String?,
    val applyCloudSchedulerProfile: suspend () -> String?,
    val saveStudyDayPolicy: suspend (String, Int) -> String?,
    val startSchedulerOptimization: () -> Unit,
    val cancelSchedulerOptimization: () -> Unit,
    val applySchedulerOptimizerCandidate: suspend (Boolean) -> String?,
    val discardSchedulerOptimizerCandidate: suspend () -> String?,
    val setPluginRendererAssignment: suspend (PluginRendererScope, String, String?) -> String?,
    val resolveSyncConflict: (SyncUploadConflict, Boolean) -> Unit,
)
